name: Cypress Tests
on: [push]
jobs:
   cypress-run:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v3.5.3
       - name: Cypress.io
         uses: cypress-io/github-action@v5.8.2
         with:
          build: npm run build
          start: npm start
          browser: chrome
           
       
